### ISSUE TITLE
Addon Icon missing in Firefox

### ISSUE THREAD

**Issue by vhugogarcia** [erikvold/chrome-tailor#29]
Hello friends,

I was able to perform the conversion and it was correctly converted and generated a .XPI file extension, I installed the addon in firefox manually, however I cannot see the icon or menu option to execute my addon.

Am I missing something?

Note: My chrome extension is the simple Popup chrome extension hello world, it has an icon in the manifest.json defined and also the physicial icon png file.

Thanks in advance

**Comment by Coding-Hen** [comment]
I have also had the same issue with this and have not found any resolve to it yet.

**Comment by vhugogarcia** [comment]
Any workaround or alternative?

**Comment by jeprince** [comment]
i'm having this problem as well. Have not figured out what is wrong yet.
